#!/usr/bin/perl -w

#   Engine1999 - A 2D games engine written in C
#   Copyright (C) 2026  Ekkehard Morgenstern
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#   NOTE: Programs created with a built-in programming language (if any),
#         do not fall under this license.
#
#   CONTACT INFO:
#       E-Mail: ekkehard@ekkehardmorgenstern.de
#       Mail: Ekkehard Morgenstern, Mozartstr. 1, D-76744 Woerth am Rhein,
#             Germany, Europe

my $byteix = 0;
my @bytes = (0) x 3072;
my $ln = 0;

open FILE,"<8x12font1.txt" || die "can't open input file: $!\n";
while (<FILE>) {
    chomp; $ln++;
    if ( /^!!/ ) {
        die "bad input file\n" unless /^!!8x12/;
        next;
    }
    if ( /^#([0-9a-fA-F]{2})/ ) {
        $byteix = eval("0x$1") * 12;
        next;
    }
    if ( /^([.o]{8})/ ) {
        my $tmp = $1;
        $tmp =~ tr/.o/01/;
        $bytes[$byteix++] = eval "0b$tmp";
        last if $byteix >= 3072;
        next;
    }
    next if /^\s*$/;
    print "line $ln unaccounted for: $_\n";
}
close FILE;

open FILE,'>8x12font1.c' || die "couldn't create output file: $!\n";
print FILE "// auto-generated by fontcomp.pl -- DO NOT MODIFY!\n\n";
print FILE "#include \"stdtypes.h\"\n\n";
$byteix = 3072;
print FILE "const uint8_t fontdef1[$byteix] = {\n";
for ( my $i=0; $i < $byteix; $i += 12 ) {
    my $hexes = '';
    for ( my $j=0; $j < 12; $j++ ) {
        $hexes .= ',' if $j > 0;
        $hexes .= sprintf( "0x%02x", $bytes[$i+$j] );
    }
    $comma = ",";
    if ( $i + 12 >= $byteix ) {
        $comma = "";
    }
    print FILE "    $hexes$comma\n";
}
print FILE "};\n\n";
close FILE;
